// Enable all RTC SDK debug logs
{.$DEFINE RTC_DEBUG}

// Compile for deployment
{.$DEFINE RtcDeploy}

 // Compile for testing
{.$DEFINE RtcTest}

// Enable extended Session destructor debug logging
{.$DEFINE RTC_EXTDEBUG}

// Compile with StreamSec Tools II
{.$DEFINE StreamSecII}

// Compile package for FireMonkey iOS
{.$DEFINE RTC_FMI}

// Compile package for FireMonkey Win32, Win64 and OSX
{.$DEFINE RTC_FMX}